name: Publish

on:
  release:
    types: [published]

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build
        run: yarn build

      - name: Get version from tag
        id: version
        uses: actions/github-script@v6
        with:
          script: "require('./.github/scripts/get-version')({ core, tag: '${{ github.event.release.tag_name }}' })"

      - name: Set git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update version
        run: |
          yarn config set version-git-message "release: v${{ steps.version.outputs.value }} [skip ci]"
          yarn version --new-version ${{ steps.version.outputs.value }}

      - name: Publish to NPM
        run: yarn publish

      - name: Push version changes
        run: git push origin main
